server:
  port: 8084

# EUREKA
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaultZone: http://localhost:8761/eureka/

# Подключение к aws DB
#spring:
  #application:
    #name: app-service
  #datasource:
    #url: jdbc:postgresql://database-1.cpmu602sigzc.eu-north-1.rds.amazonaws.com:5432/postgres
    #username: postgres
    #password: adminadmin
    #hikari:
      #auto-commit: false


spring:
  application:
    name: app-service
  datasource:
    url: jdbc:postgresql://localhost:5432/serviceAppDB
    username: postgres
    password: password
    hikari:
      auto-commit: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    queue:
      name: notification-queue
      exchangeName: notification-exchange
      routingKey: notification-key

  sendgrid:
    is-enable: false

#  jpa:
#    hibernate:
#      archive.autodetection: class,hbm
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

  logging:
    level:
      org.springframework.security: DEBUG

# ZIPKIN
management:
  tracing:
    sampling:
      probability: 1.0


