package com.example.chatservice.models

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import java.util.*

@DynamoDBTable(tableName = "Chats")
data class ChatModel(
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "chat_id")
    var chatId: String,

    @DynamoDBAttribute(attributeName = "tasker_id")
    var taskerId: String,

    @DynamoDBAttribute(attributeName = "customer_id")
    var customerId: String,
)
