package com.example.chatservice.models
import com.amazonaws.services.dynamodbv2.datamodeling.*
import java.time.LocalDateTime
import java.util.*


@DynamoDBTable(tableName = "Messages")
data class MessageModel(

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "chat_id")
    val chatId: String,

    @DynamoDBAttribute(attributeName = "message_text")
    val messageText: String,

    @DynamoDBAttribute(attributeName = "send_time")
    val sendTime: String,

    @DynamoDBAttribute(attributeName = "user_id")
    val userId: String,

    @DynamoDBAttribute(attributeName = "message_id")
    val messageId: String,

    @DynamoDBAttribute(attributeName = "delivered")
    var delivered: Boolean,

    @DynamoDBAttribute(attributeName = "seen")
    var seen: Boolean,

    @DynamoDBAttribute(attributeName = "receiver_id")
    val receiverId: String
)
